# Generated by Django 5.1.3 on 2024-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_portafolio', '0002_project_experience_achievements_experience_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/projects/images/'),
        ),
    ]
