# Generated by Django 5.1.3 on 2024-11-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_portafolio', '0003_remove_experience_achievements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
