# Generated by Django 5.1.3 on 2024-11-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_portafolio', '0004_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place_studies', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
